### ISSUE TITLE
Sugestões - Aula 03_importacao.qmd

### ISSUE THREAD

**Issue by jtrecenti** [ipeadata-lab/curso_r_intro_202409#1]
Arquivo: https://github.com/ipeadata-lab/curso_r_intro_202409/blob/main/03_importacao.qmd

- [x] Nessa linha:

https://github.com/ipeadata-lab/curso_r_intro_202409/blob/5c68c24a340a0c8ec66b4bbf9690ed9b09237935/03_importacao.qmd#L20

Sugiro comentar que estamos levando os dados para a memória RAM.

- [x] Perto daqui:

https://github.com/ipeadata-lab/curso_r_intro_202409/blob/5c68c24a340a0c8ec66b4bbf9690ed9b09237935/03_importacao.qmd#L69

Sugiro incluir uma caixa de aviso comentando sobre a importância de usar caminhos relativos e projetos

- [x] Aqui:

https://github.com/ipeadata-lab/curso_r_intro_202409/blob/5c68c24a340a0c8ec66b4bbf9690ed9b09237935/03_importacao.qmd#L111

Sugeriria explicar o que é um arquivo binário e explicar que existem diferentes tipos de binários no R, como .Rdata e formatos externos, como .feather e .parquet, mas que vocês não falarão sobre isso agora.

- [x] typo

https://github.com/ipeadata-lab/curso_r_intro_202409/blob/5c68c24a340a0c8ec66b4bbf9690ed9b09237935/03_importacao.qmd#L132

- [x] itemização quebrada

https://github.com/ipeadata-lab/curso_r_intro_202409/blob/5c68c24a340a0c8ec66b4bbf9690ed9b09237935/03_importacao.qmd#L136C1-L137C1

- [x] target _blank em links externos, exemplo abaixo

https://github.com/ipeadata-lab/curso_r_intro_202409/blob/5c68c24a340a0c8ec66b4bbf9690ed9b09237935/03_importacao.qmd#L210C1-L211C1

- [x] usar str_split?

https://github.com/ipeadata-lab/curso_r_intro_202409/blob/5c68c24a340a0c8ec66b4bbf9690ed9b09237935/03_importacao.qmd#L260

**Comment by beatrizmilz** [comment]
Obrigada pelas sugestões! Já arrumei algumas, e outras ainda preciso arrumar.

Coloquei no README os arquivos que já avancei, caso você queira dar o feedback também!
https://github.com/ipeadata-lab/curso_r_intro_202409/blob/main/README.md

@jtrecenti
