### ISSUE TITLE
usar {renv} na gestão do repo

### ISSUE THREAD

**Issue by rafapereirabr** [ipeadata-lab/curso_r_intro_202409#10]
Oi @beatrizmilz , se voce ja tem familiariedade com o pacote [{renv}](https://rstudio.github.io/renv/articles/renv.html), eu sugiro a gente usar na gestão desse repo. Isso ajuda a garantir que a gente tem todos os pacotes instalados (e na mesma versa), o que é importante para ter certeza de que tudo vai ser renderizado sem problema. Por exemplo, acabei de ver aqui que [um gráfico da seção do censobr nao](https://ipeadata-lab.github.io/curso_r_intro_202409/11_censobr_microdados.html#saneamento) rodou pq a maquina que compilou o site nao tinha o pacote `quantreg`

> Warning: Computation failed in `stat_boxplot()`.
> Caused by error in `loadNamespace()`:
> ! there is no package called 'quantreg'

**Comment by beatrizmilz** [comment]
Oi Rafael! @rafapereirabr 
Sobre o erro do `quantreg`, eu atualizei o R na semana passada e todos os pacotes precisam ser instalados novamente. Então como esse eu ainda não tinha usado, não estava instalado e acabou gerando esse erro. Instalei ele aqui.


Sobre o renv, é uma boa ideia! Fiz essa atualização.

Porém parece que como o quantreg não está sendo usado ativamente no script, pelo que entendi o renv tá indicando que ele não está sendo usado. 
```
> renv::snapshot()
The following package(s) will be updated in the lockfile:

# CRAN ------------------------------------------------------
- MatrixModels   [0.5-3 -> *]
- quantreg       [5.98 -> *]
- SparseM        [1.84-2 -> *]
- survival       [3.6-4 -> *]

Do you want to proceed? [Y/n]: n

- Operation canceled.
```


Tudo bem se eu colocar um `library(quantreg)` no chunk `load-libraries` no script 11_censobr_microdados.qmd?

https://github.com/ipeadata-lab/curso_r_intro_202409/blob/aa85dfe7e077dae00dc00b8bcb6c28112508ca06/11_censobr_microdados.qmd#L173-L180

**Comment by rafapereirabr** [comment]
pois eh, esse {quantreg} é usado internamente pelo ggplot na hora de fazer o boxplot com ponderação. Dai costuma dar esse probleminha

**Comment by rafapereirabr** [comment]
valeu! vou dar um `renv::restore()` aqui e entar resolver aquele issue do `code-annotations`. Podemos fehcar esse issue aqui
