### ISSUE TITLE
problema com o `code-annotations`

### ISSUE THREAD

**Issue by rafapereirabr** [ipeadata-lab/curso_r_intro_202409#11]
A função de `code-annotations` só está disponível para no Quarto a partir da versão [v1.3](https://quarto.org/docs/blog/posts/2023-03-13-code-annotation/).

Veja qual versão voce esta usando com `quarto::quarto_version()`

**Comment by beatrizmilz** [comment]
Exemplo de como está aparecendo:

![imagem](https://github.com/user-attachments/assets/aa6fa814-65ec-4cf2-9503-f785ca575bab)


A versão que estou usando é a 1.4.549:
```
> quarto::quarto_version()
[1] ‘1.4.549’
```

**Comment by rafapereirabr** [comment]
fui renderizar o site localmente e apareceu essa mensagem aqui:

`"Since code annotations are present, code-linking has been disabled"`. 

Não sei muito o que fazer com isso, mas é uma pista lol

**Comment by beatrizmilz** [comment]
Desabilitei o code-link e parece que agora foi!

https://ipeadata-lab.github.io/curso_r_intro_202409/03_importacao.html#importando-dados-usando-pacotes-de-dados

Aparentemente não é possível usar as duas funcionalidades de uma vez!

![Captura de Tela 2024-09-30 às 13 30 02](https://github.com/user-attachments/assets/d3395f54-03ea-4fe4-859c-3630b349ae01)

**Comment by rafapereirabr** [comment]
ah, otimo! podemos fechar aqui entao!
