### ISSUE TITLE
Sugestões 02_conceitos_basicos_r

### ISSUE THREAD

**Issue by beatrizmilz** [ipeadata-lab/curso_r_intro_202409#15]
@jtrecenti 
- [x] Faltou "R como calculadora"
- [x] Em "consultando os objetos criados", citei o global environment. Mas é realmente necessário explicar o que é o global environment? melhor citar apenas Painel Environment
- [x] removendo objetos: objeto pkgs -> nao é mais o pkgs
- [x] o texto do "removendo objetos", seria bom citar a opção de não salvar o .Rdata. 
- [x]  podemos citar também o Zen do R sobre o .Rdata
-  Julio acha muita informação em "nomeando objetos", não essencial. Pensar. Eu acho importante. 
- [x] no tipo lógico, substituir "binário" por "booleano"
- [x] quando falar do tipo data, date é com D maiúsculo.
- [x] adicionar mais uma operação com datas: dia + 1; 28 de fev + 1; 29 fev + 1
- [x] adicionar a regra de coerção: logico > inteiro > numerico > texto
- [x] Júlio acha que não é necessário falar de matrizes, não usaremos no curso.
- [x] em listas: tem palavras duplicadas. "as listas são objetos..."
- [x] citar o style guide em materiais extras

**Comment by beatrizmilz** [comment]
Sobre essa sugestão:
>  Júlio acha que não é necessário falar de matrizes, não usaremos no curso.

@rafapereirabr Comentei o trecho de código que fala sobre matrizes. Se acharem importante citar, posso "descomentar" o trecho.

**Comment by beatrizmilz** [comment]
Sobre essa sugestão:

>  Julio acha muita informação em "nomeando objetos", não essencial. Pensar. Eu acho importante.

@rafapereirabr Escolhi manter, mas caso vocês achem desnecessário, posso remover.

**Comment by beatrizmilz** [comment]
Obrigada pelas sugestões @jtrecenti ! Fiz as modificações mas vou deixar a issue aberta um tempo para que o Rafa consiga ver os comentários.

**Comment by rafapereirabr** [comment]
Oi pessoal. Dei uma olhada agora na seção 2 de conceitos básicos e me parece Ok. Concordo que a parte sobre como 'nomear objetos' não é estritamente necessária. Mas nesses casos, acho que o melhor é deixar o conteúdo no site, mas não gastar muito tempo com isso durante a aulda
