### ISSUE TITLE
Equipe na página inicial

### ISSUE THREAD

**Issue by beatrizmilz** [ipeadata-lab/curso_r_intro_202409#2]
@cavalcanti1985 @rafapereirabr

Oi pessoal, tudo bem?
Eu ia fazer essa pergunta na reunião, mas acho que é mais fácil fazer por aqui.

Para a página do curso, estou buscando seguir a estrutura da oficina do `{censobr}` que o Rafael compartilhou.

Na página inicial, aparece o nome das pessoas que vão ministrar. No nosso caso, eu pensei que seria interessante colocar o nome de vocês também, pois estão na organização do curso, vão participar do lado presencial, estamos desenvolvendo a ideia dos materiais juntos, enfim.

O que acham?

https://github.com/ipeadata-lab/curso_r_intro_202409/blob/a7f4802eb854c5dd316c0bdfae658e223fac2d01/index.qmd#L19-L28

**Comment by cavalcanti1985** [comment]
Acho uma boa ideia colocar nossos nomes. O que acha, @rafapereirabr?

**Comment by rafapereirabr** [comment]
ok por mim! Obrigado @beatrizmilz !

**Comment by beatrizmilz** [comment]
Adicionei vocês!

Fiquem à vontade para alterar se quiserem.
Os links do Rafael eu copiei da atividade do censobr.

Do Pedro eu peguei algumas coisas que encontrei, então se quiser complementar (ou remover alguma coisa que não usa), fica a vontade para alterar ou me avisar para mudar também!


https://github.com/ipeadata-lab/curso_r_intro_202409/blob/985525caffe36ccca6947d9403a5575fafbfd172/index.qmd#L21-L41
