### ISSUE TITLE
Adicionar workflow de renderização

### ISSUE THREAD

**Issue by beatrizmilz** [ipeadata-lab/curso_r_intro_202409#20]

**Comment by beatrizmilz** [comment]
Pessoal, adicionei o workflow do actions!
Agora a ideia é que não precisamos rodar mais `quarto render` localmente, apenas precisamos enviar os arquivos `.qmd` alterados e o actions vai renderizar o site.
Marcando o @cavalcanti1985 para saber que nas próximas pode fazer as alterações sem que eu precise renderizar local!

**Comment by beatrizmilz** [comment]
Achei que tinha dado certo mas ainda não foi..
deu um problema de permissão, e eu não tenho acesso para mudar.


```
origin	https://github.com/ipeadata-lab/curso_r_intro_202409 (push)
remote: Permission to ipeadata-lab/curso_r_intro_202409.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/ipeadata-lab/curso_r_intro_202409/': The requested URL returned error: 403
```


Depois alguém que tenha acesso consegue checar se o Workflow tem permissão read/write?
Nessa página:
https://github.com/ipeadata-lab/curso_r_intro_202409/settings/actions

![imagem](https://github.com/user-attachments/assets/49a5b532-916d-4001-a764-48df444e47cf)
Obrigada!

**Comment by rafapereirabr** [comment]
oi @beatrizmilz ! Eu Estranhamente, essa opção não está disponivel para mim, apesar de eu ser 'admin' do repositorio e um dos owners do grupo ipeadata-lab
 
<img width="610" alt="Screenshot 2024-10-24 222137" src="https://github.com/user-attachments/assets/c394d407-ba1e-4fdf-afb3-506f126b56e8">

**Comment by cavalcanti1985** [comment]
Pessoal, resolvido. As permissões precisavam ser alteradas nas configurações gerais do ipeadat-lab.

**Comment by beatrizmilz** [comment]
Obrigada Pedro!
Eu vi que o workflow deu um problema e que você já resolveu também! Obrigada!
