### ISSUE TITLE
disponibilização dos dados

### ISSUE THREAD

**Issue by rafapereirabr** [ipeadata-lab/curso_r_intro_202409#4]
https://github.com/ipeadata-lab/curso_r_intro_202409/blob/8e964101764db926df2bb683405988733f3eecb3/03_importacao.qmd#L73

Oi @beatrizmilz ! Vi nessa linha acima do código que você ilustra para os usuários como se pode ler um arquivo `.csv` usando como exemplo um arquivo salvo em `"dados/sidrar_4092.csv"` do repositorio do Github. Para o pessoal conseguir rodar isso, eles vão precisar ter esse arquivos (e os outros do curso) localmente nas maquinas deles.

Como você esta pensando em disponibilizar isso para eles?

**Comment by beatrizmilz** [comment]
Rafael, bem observado! 
Na maior parte dos cursos que eu ministro (sozinha ou com outras pessoas) a abordagem é disponbilizar um projeto do RStudio já com as pastas criadas e dados salvos. PORÉM, a sensação que eu tenho é que muitas dúvidas surgem depois. Pensei então em fazer o projeto durante o curso, e salvar os arquivos a partir do repositório do GitHub.
Você acha essa abordagem muito complexa? 


Fiz algumas mudanças sobre isso, me diga o que acha:

Na aula que falaremos sobre projetos do RStudio, vamos criar um projeto:

https://github.com/ipeadata-lab/curso_r_intro_202409/blob/fac8e2735621cbc9abcdc41468fde97b8677f0f1/01_1_rproj.qmd#L90-L131

Antes de importar os dados, indiquei onde podemos baixá-los:

https://github.com/ipeadata-lab/curso_r_intro_202409/blob/fac8e2735621cbc9abcdc41468fde97b8677f0f1/03_importacao.qmd#L34-L72

**Comment by rafapereirabr** [comment]
acho que assim fica bom !
